### ISSUE TITLE
Messages object no longer shows quoted message

### ISSUE THREAD

**Issue by GabrielBragaGit** [orkestral/venom#1339]
## Description
Sorry to bring it back, but when receiving a message, the message object is expected to show the property "quotedMsgObj", to identify the replied message, but this behavior is not happening. Additionally I noticed that when using client.returnReply (message) it always returns false.

## Environment
* **Venom version(s):** 4.0.3
* **Browser:** Chrome 96.0.4664.45
* **OS:** Ubuntu 20.04.3 LTS
* **Node version:** 16.13.0

## Steps to Reproduce
1. Receive a message with onMessage  event

## Example
These are the properties that come in the chat message (even if it is a reply)

```yaml

{
  id: 'false_5521xxxxxxxx@c.us_3EB01889D197BADD9A88',
  from: '55219xxxxxxxx@c.us',
  quotedParticipant: '3519xxxxxxxx@c.us',
  chatId: '55219xxxxxxxx@c.us',
  to: '3519xxxxxxxx@c.us',
  fromMe: false,
  sender: {
    id: '55219xxxxxxxx@c.us',
    pushname: 'Gabriel Braga',
    type: 'in',
    isBusiness: false,
    isEnterprise: false,
    statusMute: false,
    labels: [],
    disappearingModeDuration: 0,
    disappearingModeSettingTimestamp: 0,
    formattedName: '+55 21 9xxxx-xxxx',
    displayName: 'Gabriel Braga',
    formattedShortName: '+55 21 9xxxx-xxxx',
    formattedShortNameWithNonBreakingSpaces: '+55 21 9xxxx-xxxx',
    isMe: false,
    mentionName: 'Gabriel Braga',
    notifyName: 'Gabriel Braga',
    isMyContact: false,
    isPSA: false,
    isUser: true,
    isWAContact: true,
    profilePicThumbObj: {
      eurl: 'XXXXXXXXX',
      id: '55219xxxxxxxx@c.us',
      img: 'XXXXXXXXX',
      imgFull: 'XXXXXXXXX',
      raw: null,
      tag: '158360xxxx'
    },
    msgs: null
  },
  timestamp: 1638387977,
  content: 'okkkkkkkkkkkkkkk',
  body: 'okkkkkkkkkkkkkkk',
  isGroupMsg: false,
  isMedia: false,
  isNotification: false,
  isPSA: false,
  type: 'chat',
  chat: {
    id: '55219xxxxxxxx@c.us',
    pendingMsgs: false,
    lastReceivedKey: {
      fromMe: false,
      remote: '55219xxxxxxxx@c.us',
      id: '3EB0A3E7E04B615DD19D',
      _serialized: 'false_55219xxxxxxxx@c.us_3EB0A3E7E04B615DD19D'
    },
    t: 1638386115,
    unreadCount: 2,
    archive: false,
    isReadOnly: false,
    muteExpiration: 0,
    notSpam: true,
    pin: 0,
    ephemeralDuration: 0,
    ephemeralSettingTimestamp: 0,
    hasUnreadMention: false,
    archiveAtMentionViewedInDrawer: false,
    hasChatBeenOpened: false,
    msgs: null,
    kind: 'chat',
    isGroup: false,
    contact: {
      id: '55219xxxxxxxx@c.us',
      pushname: 'Gabriel Braga',
      type: 'in',
      isBusiness: false,
      isEnterprise: false,
      statusMute: false,
      labels: [],
      disappearingModeDuration: 0,
      disappearingModeSettingTimestamp: 0,
      formattedName: '+55 21 9xxxx-xxxx',
      displayName: 'Gabriel Braga',
      formattedShortName: '+55 21 9xxxx-xxxx',
      formattedShortNameWithNonBreakingSpaces: '+55 21 9xxxx-xxxx',
      isMe: false,
      mentionName: 'Gabriel Braga',
      notifyName: 'Gabriel Braga',
      isMyContact: false,
      isPSA: false,
      isUser: true,
      isWAContact: true,
      profilePicThumbObj: [Object],
      msgs: null
    },
    groupMetadata: null,
    presence: { id: '55219xxxxxxxx@c.us', chatstates: [] },
    isOnline: true,
    lastSeen: null
  },
  isOnline: true,
  lastSeen: null,
  mediaData: {},
  t: 1638387977,
  isNewMsg: true,
  linkPreview: false,
  text: 'okkkkkkkkkkkkkkk',
  self: 'in',
  initialPageSize: 768
}

```
